# Generated by Django 5.0.3 on 2024-09-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(default='default_book_id', max_length=300)),
                ('review_author', models.CharField(max_length=200)),
                ('review_date', models.DateField(blank=True, default=None, null=True)),
                ('review_comment', models.CharField(max_length=500)),
            ],
        ),
    ]
